/**
 * Phase 9 — Validation gate.
 *
 * Per audits/t3-poker/06-dave-fix-prompt.md Phase 9:
 *   "Before saying this is fixed, provide evidence for:
 *     1. Backend typecheck passing.
 *     2. Poker/accounting unit tests passing.
 *     3. Integration tests for create/join/start/hand/cashout.
 *     4. 8-player manual or automated flow.
 *     5. Deposit/withdrawal testnet/fork flow if crypto path is touched.
 *     6. A short changelog listing exactly what changed and what was
 *        intentionally not changed."
 *
 * This script runs items 1-4 automatically and writes the results into
 * audits/t3-poker/07-phase9-validation-report.md (item 6).
 *
 * Item 5 (testnet) is out of scope for the script — it requires a real
 * wallet + chain, which Shaun must run. The report calls that out
 * explicitly.
 */

import { spawnSync } from 'node:child_process';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

interface StepResult {
  name: string;
  command: string;
  ok: boolean;
  durationMs: number;
  // Trailing portion of stdout/stderr captured for the report.
  output: string;
}

const BACKEND_ROOT = resolve(__dirname, '..');
// scripts/ -> packages/backend -> packages -> poker -> workspace-dave
// We want sibling workspace-gerald/audits/t3-poker.
// Walk: scripts -> backend (1) -> packages (2) -> poker (3) -> workspace-dave (4) -> openclaw root.
const OPENCLAW_ROOT = resolve(__dirname, '../../../../..');
const REPORT_PATH = resolve(
  OPENCLAW_ROOT,
  'workspace-gerald/audits/t3-poker/07-phase9-validation-report.md'
);

function run(name: string, command: string, args: string[]): StepResult {
  const started = Date.now();
  // Windows: npx is npx.cmd; spawnSync needs shell=true to resolve .cmd.
  // POSIX: shell=true is harmless. Either way, we route through the shell
  // so the gate works on Windows + macOS + Linux uniformly.
  const result = spawnSync(command, args, {
    cwd: BACKEND_ROOT,
    shell: true,
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
    env: { ...process.env, FORCE_COLOR: '0' },
  });
  const durationMs = Date.now() - started;
  const stdout = result.stdout ?? '';
  const stderr = result.stderr ?? '';
  // Strip ANSI color escapes so the report is readable in any viewer.
  const ansi = /\x1B\[[0-9;]*[A-Za-z]/g;
  const out = (stdout + stderr).replace(ansi, '');
  // Filter the noisy per-test logger lines (timestamps, BETTING:, TIMING:,
  // HandEvent breadcrumbs etc.). Keep only meaningful summary/result lines.
  const lines = out.split('\n').filter((l) => {
    if (/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/.test(l)) return false; // logger
    if (/^stdout \|/.test(l)) return false; // vitest stream prefix
    if (/^stderr \|/.test(l)) return false;
    if (/Pot \d+ awarded/.test(l)) return false;
    if (/HAND INIT|Blinds posted|Game completed|Game created|Player joined/.test(l)) return false;
    if (/Cleaning up|Auto-start|Hand completed|Showdown complete|Side pots|Advanced/.test(l)) return false;
    return true;
  });
  const tail = lines.slice(-40).join('\n').trim();
  return {
    name,
    command: `${command} ${args.join(' ')}`,
    ok: result.status === 0,
    durationMs,
    output: tail,
  };
}

function fmtDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

function buildReport(steps: StepResult[]): string {
  const allPassed = steps.every((s) => s.ok);
  const ts = new Date().toISOString();
  let md = '';
  md += `# T3 Poker — Phase 9 validation report\n\n`;
  md += `**Run timestamp**: ${ts}\n`;
  md += `**Branch**: fix/phase1-chip-accounting\n`;
  md += `**Overall verdict**: ${allPassed ? '✅ PASS' : '❌ FAIL'}\n\n`;
  md += `Generated by \`npm run validate\` (packages/backend/scripts/validate.ts).\n\n`;

  md += `## Gate items\n\n`;
  md += `| # | Item | Status | Duration |\n`;
  md += `|---|---|---|---|\n`;
  for (let i = 0; i < steps.length; i++) {
    const s = steps[i];
    md += `| ${i + 1} | ${s.name} | ${s.ok ? '✅ PASS' : '❌ FAIL'} | ${fmtDuration(s.durationMs)} |\n`;
  }
  md += `| 5 | Crypto deposit/withdrawal testnet flow | ⏸️ MANUAL | — |\n`;
  md += `\n`;
  md += `Item 5 requires a live testnet wallet + RPC and is intentionally\n`;
  md += `out of scope for the automated gate. See "Manual gate items" below.\n\n`;

  md += `## Per-step output\n\n`;
  for (const s of steps) {
    md += `### ${s.name}\n\n`;
    md += `Command: \`${s.command}\`\n\n`;
    md += `Result: ${s.ok ? '✅ PASS' : '❌ FAIL'} (${fmtDuration(s.durationMs)})\n\n`;
    md += `\`\`\`\n${s.output}\n\`\`\`\n\n`;
  }

  md += `## Phases delivered on this branch\n\n`;
  md += `| Phase | Finding | Status | Tests |\n`;
  md += `|---|---|---|---|\n`;
  md += `| 1 | [C-01] Hand winners credited to both stack and balance | ✅ Fixed | 5 |\n`;
  md += `| 2 | [H-01] Oversize raise corrupts currentBet | ✅ Fixed | 7 |\n`;
  md += `| 2 | [M-01] Short all-in incorrectly reopens action | ✅ Fixed | (covered above) |\n`;
  md += `| 3 | [H-02] Hand-action races / double-apply | ✅ Fixed | 2 |\n`;
  md += `| 4 | [H-03] Any authed socket can join any game room | ✅ Fixed | 6 |\n`;
  md += `| 5 | [H-05] Game start not atomic with first hand | ✅ Fixed | 4 |\n`;
  md += `| 6 | [M-03] maxPlayers default 9 | ✅ Hard-capped at 8 | 3 |\n`;
  md += `| 6 | [M-04] Auto-start on by default | ✅ Now opt-in | (covered above) |\n`;
  md += `| 7 | [M-05] Insufficient hand audit trail | ✅ HandEvent ledger added | 10 |\n`;
  md += `| 8 | [H-04] Loose deposit authorization | ✅ Strict signed challenge | 10 |\n`;
  md += `| Sim | (Shaun's request) Match harness | ✅ Built | 6 + 3 integration |\n`;
  md += `\n`;

  md += `## Out of scope on this branch\n\n`;
  md += `Per Gerald's prompt "Do not spend time on yet":\n`;
  md += `- Visual redesign\n`;
  md += `- New game modes / tournament support\n`;
  md += `- Spectator support (only secure rejection added)\n`;
  md += `- Advanced analytics dashboards\n`;
  md += `- Scaling beyond 8 players\n`;
  md += `- EIP-712 deposit auth (Shaun chose secondary signed-challenge option)\n`;
  md += `- Reopening edge: post-short-all-in, the prior aggressor still cannot\n`;
  md += `  legally re-raise per the min-raise gate, but a fully WSOP-compliant\n`;
  md += `  block on their right to re-raise is deferred (noted in MEMORY.md).\n\n`;

  md += `## Manual gate items (item 5)\n\n`;
  md += `Required before real-money production cutover:\n`;
  md += `1. Deposit on a testnet (e.g. Sepolia / local Anvil fork): create challenge,\n`;
  md += `   sign with a real wallet, post back to the API, send the deposit tx,\n`;
  md += `   confirm credit appears exactly once. Repeat the tx (replay) to confirm\n`;
  md += `   the second credit is rejected by the txHash idempotency check.\n`;
  md += `2. Withdrawal on the same testnet: confirm balance moves off-table back\n`;
  md += `   to the wallet, audit row exists, ledger row exists.\n`;
  md += `3. 8-player live session in dev environment: open the deployed preview,\n`;
  md += `   seat 8 humans/bots, play 5+ hands including all-ins and showdowns,\n`;
  md += `   confirm UI/UX matches the new server semantics (currentBet, fold-win,\n`;
  md += `   atomic start, socket auth).\n\n`;
  md += `When those three are signed off, send this branch back to Gerald for\n`;
  md += `re-audit, then merge to main.\n`;

  return md;
}

function main() {
  console.log('Phase 9 validation gate — running...');

  const steps: StepResult[] = [];

  // 1) Typecheck
  steps.push(run('Backend typecheck (tsc --noEmit)', 'npx', ['tsc', '--noEmit']));

  // 2 + 3 + 4) Vitest run-all (covers unit + sim + integration in one call)
  steps.push(run('All vitest suites (unit + simulator + integration)', 'npx', ['vitest', 'run']));

  // Optional lint, non-blocking — runs but does not fail the gate.
  // (Wrapped in a soft step that logs result but doesn't gate.)
  // Skipped here to keep the gate strict; can be added later.

  const report = buildReport(steps);

  const reportDir = dirname(REPORT_PATH);
  if (!existsSync(reportDir)) {
    mkdirSync(reportDir, { recursive: true });
  }
  writeFileSync(REPORT_PATH, report, 'utf8');
  console.log(`Wrote validation report -> ${REPORT_PATH}`);

  const allPassed = steps.every((s) => s.ok);
  if (!allPassed) {
    console.error('❌ Validation gate FAILED. See report for details.');
    process.exit(1);
  }
  console.log('✅ Validation gate PASSED.');
}

main();
